version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: logs_vector_db
    ports:
      - "5432:5432"             
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=log_analysis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: